services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/chatApp
      PORT: 5000
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      API_URL: http://localhost:5000
      WS_HOST: localhost:5000
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5173
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: